"""empty message

Revision ID: 68b6b86d59d6
Revises: 7de1b6c599e3
Create Date: 2020-10-09 12:49:45.749055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b6b86d59d6'
down_revision = '7de1b6c599e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ffsplayers', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ffsplayers', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('ffsplayers', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('ffsplayers_league_id_fkey', 'ffsplayers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('ffsplayers_league_id_fkey', 'ffsplayers', 'leagues', ['league_id'], ['id'])
    op.alter_column('ffsplayers', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ffsplayers', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ffsplayers', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
