"""empty message

Revision ID: f5d336ff7892
Revises: f9784b3eb8b1
Create Date: 2020-10-12 13:04:12.819184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5d336ff7892'
down_revision = 'f9784b3eb8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'college',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('players', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('players', 'height',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('players', 'weight',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'weight',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('players', 'height',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('players', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('players', 'college',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
