"""empty message

Revision ID: 7de1b6c599e3
Revises: 1758e8a42e37
Create Date: 2020-10-09 12:47:22.183955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7de1b6c599e3'
down_revision = '1758e8a42e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ffsplayers', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ffsplayers', 'leagues', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ffsplayers', type_='foreignkey')
    op.drop_column('ffsplayers', 'league_id')
    # ### end Alembic commands ###
