"""empty message

Revision ID: ffba447af0be
Revises: 5026fc8566a9
Create Date: 2020-10-18 22:10:44.086315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffba447af0be'
down_revision = '5026fc8566a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_league_fk', 'ffsplayers', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('team_league_fk', 'ffsplayers', 'teams', ['team_id', 'league_id'], ['id', 'league_id'])
    # ### end Alembic commands ###
